service: "my-express-app"

provider:
  name: aws
  runtime: node22.x
  region: us-east-1
  timeout: 10




functions:
  app:
    handler: handler.handler 
    events: 
      - http:
          method: ANY   
          path: /{proxy+}


plugins:
  - serverless-express